# permissions for end users to edit disks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disk-editor-role
rules:
- apiGroups:
  - disk8s.plockc.github.io
  resources:
  - disks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - disk8s.plockc.github.io
  resources:
  - disks/status
  verbs:
  - get
