---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - disk8s.plockc.github.io
  resources:
  - disks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - disk8s.plockc.github.io
  resources:
  - disks/finalizers
  verbs:
  - update
- apiGroups:
  - disk8s.plockc.github.io
  resources:
  - disks/status
  verbs:
  - get
  - patch
  - update
