version: v2beta1
name: nbdgit

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      create_deployments --all     # 2. Deploy Helm charts and manifests specfied as "deployments"
      start_dev app                # 3. Start dev mode "app" (see "dev" section)
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  deploy:
    run: |-
      # this container deployed through parent controller, so just build the image so it is ready
      run_pipelines build
  build:
    run: |-
      run_pipelines protobuf
      build_images --all --skip-push
  build-all:
    run: |-
      run_dependency_pipelines --pipeline build replica
      run_pipelines protobuf
      build_images --all --skip-push
  protobuf:
    run: |-
      run_dependency_pipelines --pipeline protobuf replica
  push:
    run: |-
      git diff --quiet || echo Workspace is dirty, cannot push && exit 1
      # check it compiles first
      devspace run protobuf
      run_dependency_pipelines --pipeline build replica
      build_images --all --skip-push
      # start pushing
      git diff --quiet || echo Workspace is dirty, cannot push && exit 1
      run_dependency_pipelines --pipeline push replica
      build_images --all

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  app:
    image: plockc/nbd-server:latest
    dockerfile: ./Dockerfile
    tags:
      - latest
      - $(git describe --always --dirty)

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    # Search for the container that runs this image
    #imageSelector: nbd-server:latest
    labelSelector:
      nbd-server: sample
    # Replace the container image with this dev-optimized image (allows to skip image building during development)
    devImage: ghcr.io/loft-sh/devspace-containers/go:1.18-alpine
    # Sync files between the local filesystem and the development container
    persistPaths:
      - path: /go/pkg/mod/cache/download
    sync:
      - path: ./
        uploadExcludeFile: .dockerignore
    # Open a terminal and use the following command to start it
    terminal:
      command: ./devspace_start.sh
    # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
    ssh:
      enabled: true
    # Make the following commands from my local machine available inside the dev container
    proxyCommands:
      - command: kubectl
      - command: helm
      - command: git
    # Forward the following ports to be able access your application via localhost
    ports:
      - port: "10809"

# Use the `commands` section to define repeatable dev workflows for this project 
commands:
  protobuf:
    command: devspace run-pipeline protobuf

dependencies:
  replica:
    path: ./replica
