# permissions for end users to view disks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: disk-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: disk-viewer-role
rules:
- apiGroups:
  - disk8s.plockc.org
  resources:
  - disks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - disk8s.plockc.org
  resources:
  - disks/status
  verbs:
  - get
